---
version: "2.0"
services:
  redis:
    image: redis:7.2.4
    expose:
      - port: 6379
        as: 6379
        to:
          - global: false
          - service: server-app
          - service: worker-app
    command:
      - bash
      - "-c"
    args:
      - redis-server --requirepass yourpassword
  server-app:
    image: mrlaki5/qr-ai-generator-server:1.0.0
    expose:
      - port: 8089
        as: 80
        to:
          - global: true
    env:
      - REDIS_IP=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=yourpassword
  worker-app:
    image: mrlaki5/qr-ai-generator-worker:1.0.0
    expose:
      - port: 8088
        as: 8088
        to:
          - global: false
    env:
      - REDIS_IP=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=yourpassword
profiles:
  compute:
    redis:
      resources:
        cpu:
          units: 2
        memory:
          size: 1Gi
        storage:
          - size: 1Gi
    server-app:
      resources:
        cpu:
          units: 4
        memory:
          size: 4Gi
        storage:
          - size: 4Gi
    worker-app:
      resources:
        cpu:
          units: 8
        memory:
          size: 32Gi
        storage:
          - size: 32Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia: 
  placement:
    dcloud:
      pricing:
        redis:
          denom: uakt
          amount: 1000
        server-app:
          denom: uakt
          amount: 1000
        worker-app:
          denom: uakt
          amount: 1000
deployment:
  redis:
    dcloud:
      profile: redis
      count: 1
  server-app:
    dcloud:
      profile: server-app
      count: 1
  worker-app:
    dcloud:
      profile: worker-app
      count: 1
